project:
  type: website
  output-dir: docs

# Website title and description (optional, but useful for SEO)
title: "My Quarto Project"
description: "An analysis of SpyCATS data"

# Configuration for rendering and execution
execute:
  enabled: true
  freeze: auto

# Add any other project-specific configurations here
# ...

# If you have additional files or directories to include or exclude
# from your Quarto project, specify them here
# include:
# exclude:

# If you are using any Quarto extensions, specify them here
# extensions:

# Any additional metadata or configurations specific to your project
# ...

# You can also specify global options for formats here
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
